// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZL3_G7cWFgJwCk70bRBzs8MHVGV4XkU',
    appId: '1:966765070451:web:bb6f38fbce1cf01b520206',
    messagingSenderId: '966765070451',
    projectId: 'vitalitas-bb512',
    authDomain: 'vitalitas-bb512.firebaseapp.com',
    storageBucket: 'vitalitas-bb512.appspot.com',
    measurementId: 'G-3FE5YQQQGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8NhhZ_eN6xBHIu6dwILoxHZKrnnYIz8',
    appId: '1:966765070451:android:e727c0f0b46b0d76520206',
    messagingSenderId: '966765070451',
    projectId: 'vitalitas-bb512',
    storageBucket: 'vitalitas-bb512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf00Mm-8JUpKdvZSS2g2sfo8dg4zADDGI',
    appId: '1:966765070451:ios:7048fa79b25b5bfd520206',
    messagingSenderId: '966765070451',
    projectId: 'vitalitas-bb512',
    storageBucket: 'vitalitas-bb512.appspot.com',
    iosClientId: '966765070451-5vpltadtciboa93sb6ldm7sqk98188k3.apps.googleusercontent.com',
    iosBundleId: 'com.patetlex.vitalitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf00Mm-8JUpKdvZSS2g2sfo8dg4zADDGI',
    appId: '1:966765070451:ios:7048fa79b25b5bfd520206',
    messagingSenderId: '966765070451',
    projectId: 'vitalitas-bb512',
    storageBucket: 'vitalitas-bb512.appspot.com',
    iosClientId: '966765070451-5vpltadtciboa93sb6ldm7sqk98188k3.apps.googleusercontent.com',
    iosBundleId: 'com.patetlex.vitalitas',
  );
}
